# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f49b11426a703dec66fa30c7a730673d"
name = "inspire-test-app"
handle = "inspire-test-app"
application_url = "https://realized-obligations-killing-services.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "leonovstore.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://realized-obligations-killing-services.trycloudflare.com/auth/callback",
  "https://realized-obligations-killing-services.trycloudflare.com/auth/shopify/callback",
  "https://realized-obligations-killing-services.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
